# -*- coding: utf-8 -*-
"""
/***************************************************************************
 autoRedistrict
                                 A QGIS plugin
 Automatically splits areas into nearly equal segments
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-01-18
        copyright            : (C) 2020 by John Holden
        email                : redistricting@stattoconsulting.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load autoRedistrict class from file autoRedistrict.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .autoRedistrict import autoRedistrict
    return autoRedistrict(iface)
